import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p className={styles.button}>
            <Link id={styles.about} href="about">About</Link>
          </p>
          <div>
            <a id={styles.by}>
              By{' Wendy'}
            </a>
          </div>
        </div>

        <div className={styles.grid}>
        <div className={styles.business}>
            <div className={styles.heading}>Business Degree:</div>
            {
              information && information.map((info, index) => {
                if (info.department === "Business") {
                  return (
                    <Card key={index} degree={info.degree} colour="rgb(255 255 255 / 0%)" font="30px"/>
                  )
                }
              })
            }
          </div>
          <div className={styles.computing}>
            <div className={styles.heading}>Computing Degree:</div>
            {
              information && information.map((info, index) => {
                if (info.department.toLowerCase() === "computing") {
                  return (
                    <Card key={index} degree={info.degree} colour="rgb(255 255 255 / 0%)" font="30px" />
                  )
                }
              })
            }
          </div>
        </div>
      </main>
    </>
  )
}
